web:
  build: .
  command: 'bash -c ''java -Dserver.port=$PORT $JAVA_OPTS -jar target/demo-company-0.0.1.jar'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
